# Generated by Django 5.2.12 on 2026-03-30 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
                ('affiliation', models.CharField(max_length=150)),
                ('homeland', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=150)),
                ('element', models.CharField(max_length=100)),
                ('first_appearance', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'character',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='characters/')),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainsite.character')),
            ],
            options={
                'db_table': 'character_image',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
