# Generated by Django 5.2.12 on 2026-03-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='element',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='characterimage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
