# Generated by Django 6.0.3 on 2026-03-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0002_alter_character_element_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="characterimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
