# Generated by Django 6.0.3 on 2026-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0003_alter_character_id_alter_characterimage_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="vote_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
