# Generated by Django 6.0.3 on 2026-04-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0004_character_vote_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="mainsite.character",
                    ),
                ),
            ],
            options={
                "db_table": "character_vote",
            },
        ),
        migrations.AddConstraint(
            model_name="charactervote",
            constraint=models.UniqueConstraint(
                fields=("character", "session_key"),
                name="uniq_character_vote_per_session",
            ),
        ),
    ]
