# Generated by Django 6.0.3 on 2026-04-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0005_charactervote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("characters", "Characters"),
                            ("timeline", "Timeline"),
                            ("elements", "Elements"),
                            ("world", "World"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
